### ISSUE TITLE
Broken registration with manually set registration server IP after reboot

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE-Enceladus/cloud-regionsrv-client#27]
Filing this so that I can investigate later. The instance was registered with `--smt-ip` flag, after reboot it seems to have cleaned up registration server cache and all zypper repos/services:

```
2019-11-01 14:14:42,492 INFO:Using API: regionInfo
2019-11-01 14:14:42,618 INFO:Region server arguments: ?regionHint=westus2
2019-11-01 14:14:42,618 INFO:Using region server: 104.45.31.195
2019-11-01 14:14:43,327 INFO:Have extra cached SMT data, clearing cache
2019-11-01 14:14:43,327 INFO:Extra cached server is current registration target, cleaning up registration
2019-11-01 14:14:43,327 INFO:Clean current registration server: ('34.218.245.132', None)
```

After this, running `registercloudguest` died with a strack trace:

```
# registercloudguest 
Traceback (most recent call last):
  File "/usr/sbin/registercloudguest", line 416, in <module>
    utils.clear_new_registration_flag()
  File "/usr/lib/python3.6/site-packages/cloudregister/registerutils.py", line 132, in clear_new_registration_flag
    os.unlink(REGISTRATION_DATA_DIR + NEW_REGISTRATION_MARKER)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/cloudregister/newregistration'
```

The instance had v9.0.4 of `cloud-regionsrv-client`, this might not be an issue in the most recent version.

**Comment by ikapelyukhin** [comment]
OK, this was already fixed in [v9.0.5](https://github.com/SUSE-Enceladus/cloud-regionsrv-client/pull/19).
